type User {
  id: ID!
  name: String!
  dateOfBirth: String!
  email: String!
}

type Query {
  me: User
  login(email: String!, password: String!): AuthPayload!
  user(id: ID!): User!
}

type Mutation {
  createUser(name: String!, dateOfBirth: String!, email: String!): User!
  signup(name: String!, email: String!, password: String!, dateOfBirth: String!): AuthPayload!
  createApplication: CreateApplicationPayload!
  submitCollectIncomeApplication(input: CollectIncomeApplicationInput!): CreateApplicationPayload!
  submitEssentialExpenseApplication(input: ExpenseApplicationInput!): CreateApplicationPayload!
}

type AuthPayload {
  token: String!
  user: User!
}

enum ApplicationScreen {
  IncomeDetailScreen
  EssentialExpenseScreen
  CompletedScreen
}

enum ExpenseSource {
  ESSENTIALS
}

type CreateApplicationPayload {
  screen: ApplicationScreen
}

type ExpenseItems {
  name: String!
  amount: Int!
  source: ExpenseSource!
}

input CollectIncomeApplicationInput {
  applicationId: ID!
  incomeAmount: Int!
}

input ExpenseApplicationInput {
  applicationId: ID!
  items: ExpenseItems!
}